### PR TITLE
Fix minimal riscv defconfig

### PR DESCRIPTION
**Pull request by roman3017**

### CODE REVIEW

**Comment by Dolu1990** [comment]
Hi,

Hmm there is quite a few things which are too specific i would say, as CONFIG_SPI_SPINAL_LIB=y

Ultimately, i would try to avoid putting specific things into non specific space, to avoid forking to far away from upstream linux.

Does that make sense ?

**Comment by roman3017** [comment]
Agree, will remove CONFIG_SPI_SPINAL_LIB and CONFIG_GPIO_SPINAL_LIB.

**Comment by roman3017** [comment]
@Dolu1990 I was hoping that minimal defconfig would be a configuration, which would have just UART and rootfs either in SD or RAM. Something one would try first when bringing up new RISCV board, which could have limited resources like 8MB SDRAM. So having CONFIG_SPI_SPINAL_LIB would seem desirable or we may also remove SPI and MMC support and assume RAM only rootfs. What do you think?

**Comment by roman3017** [comment]
Will close it since defconfigs are being stored elsewhere.

**Pull request closed without merging**
